[package]
name = "downloader-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"

[dependencies]
anyhow = "1.0.93"
reqwest = "0.12.9"
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["full"] }
